routes/admin.php
<?php
Route::get('/','Admin\HomeController@home')->name('admin.home');

//notifications controller
Route::get('/messages','Admin\NotificationController@messages')->name('admin.messages');
Route::get('/annoucements','Admin\NotificationController@annoucements')->name('admin.annoucements');

Route::resources([
    'students'=>'Admin\StudentController',
    'teachers'=>'Admin\TeacherController',
    'classes'=>'Admin\ClassesController',
    'sections'=>'Admin\SectionController',
    'courses'=>'Admin\CourseController',
    'class_courses'=>'Admin\ClassCourseController',
    'accountants'=>'Admin\AccountantController',
    'slots'=>'Admin\SlotController',
    'roles'=>'Admin\RoleController',
]);
//manage employees
Route::prefix('manage-employees')->group(function (){
    Route::resources([
        'school-roles'=>'Admin\Employees\Roles\RoleController',
        'employees'=>'Admin\Employees\EmployeeController'
    ]);
    Route::get('index','Admin\Employees\IndexController@index')->name('manage.employees.index');
    Route::get('unassign-role/{user_id}/{role_id}','Admin\Employees\EmployeeController@unassignRole');
    Route::get('assign-role/{user_id}/{role_id}','Admin\Employees\EmployeeController@assignRole');
    Route::post('update-password','Admin\Employees\EmployeeController@changePassword');
});
//students routes continuation
Route::prefix('students')->group(function (){
    Route::post('/search','Admin\StudentController@searchStudent');
    Route::post('/update-password','Admin\MiscController@updateStudentPassword');
    Route::get('/unassign-guardian/{id}','Admin\MiscController@unassignGuardian');
});

//settings controllers
Route::prefix('configuration')->group(function () {
    Route::get('','Index\IndexController@adminSettings')->name('admin.configuration.index');
    Route::resources([
        'general_settings'=>'Admin\Settings\GeneralSettingsController',
        'institution_settings'=>'Admin\Settings\InstitutionSettingsController',
        'fee-approvals'=>'Admin\Settings\FeeSettingsController'
    ]);
    Route::get('student-profile-fields','Admin\Settings\StudentSettingsController@index')
        ->name('configuraton.student.profile.field');
    Route::post('student-profile-fields','Admin\Settings\StudentSettingsController@update');
});

//endpoints
Route::prefix('admin-endpoints')->group(function (){
    Route::get('states/{id}','Admin\MiscController@getStates');
});
Route::prefix('add-fields')->group(function (){
    Route::post('guardian','Admin\MiscController@addGuardian');
    Route::post('student','Admin\MiscController@addStudent');
    Route::post('search-guardian','Admin\MiscController@searchGuardian');
    Route::post('update-guardian','Admin\MiscController@getGuardian');
});


//report controllers
Route::get('/reports-attendance','Admin\ReportController@teacherAttendance')->name('admin.reports.attendance');
Route::get('/reports-marks','Admin\ReportController@teacherMarks')->name('admin.reports.marks');

//details
Route::get('/school-details','Admin\DetailController@index')->name('admin.details.index');
Route::get('/school-details/items','Admin\DetailController@itemsIndex')->name('admin.details.items');
Route::post('/school-details/items/save','Admin\DetailController@saveItem')->name('admin.details.item.save');
Route::get('/school-details/academic-years','Admin\DetailController@academicIndex')->name('admin.details.academic');
Route::post('/school-details/academic-years/save','Admin\DetailController@saveAcademicYear')->name('admin.details.academic.save');
Route::delete('/school-details/academic-years/delete/{id}','Admin\DetailController@deleteAcademicYear');
//terms routes
Route::get('/school-details/terms','Admin\DetailController@showTerms')->name('admin.details.terms');
Route::post('/school-details/terms/save','Admin\DetailController@saveTerms')->name('admin.details.terms.save');

//more items
Route::delete('/school-details/items/delete/{id}','Admin\DetailController@deleteItem');
Route::put('/school-details/items/update/{id}','Admin\DetailController@updateItem');

//fee details
Route::get('/school-details/fees','Admin\DetailController@showFees')->name('admin.details.fees');
Route::post('/school-details/fees/save','Admin\DetailController@saveFees')->name('admin.details.fees.save');
Route::delete('/school-details/fees/delete/{id}','Admin\DetailController@deleteBreakDownItem');
//filter fees
Route::post('/school-details/fees/filter','Admin\DetailController@filterFees');


///edit years
Route::get('/school-details/terms/{id}','Admin\DetailController@showEditAcademic')->name('admin.details.term.show');
Route::post('/school-details/terms/update','Admin\DetailController@updateEditAcademic')->name('admin.details.term.update');

//edit terms
Route::get('/school-details/terms-year/{id}','Admin\DetailController@showEditTerm')->name('admin.details.term.year.show');
Route::post('/school-details/terms-year/update','Admin\DetailController@updateEditTerm')->name('admin.details.term.year.update');
Route::delete('/school-details/terms-year/delete/{id}','Admin\DetailController@deleteTerm')
    ->name('admin.details.terms.delete');
Route::group(['prefix'=>'school-details'],function (){

    Route::get('all-guardians','Admin\DetailController@getAllGuardians')->name('admin.get.all.guardians');
    Route::put('all-guardians-edit/{id}','Admin\DetailController@updateGuardian');
    Route::post('all-guardians-delete','Admin\DetailController@deleteGuardian');
});
//sms routes
Route::get('sms/parents','Admin\SMSController@showParent')->name('admin.sms.parent');

//profile
Route::get('/profile','Admin\ProfileController@showProfile')->name('admin.profile.show');
Route::post('/profile','Admin\ProfileController@updateProfile')->name('admin.profile.update');
Route::get('/passwords','Admin\ProfileController@showPassword')->name('admin.passwords.show');
Route::post('/passwords','Admin\ProfileController@updatePassword')->name('admin.passwords.update');

//receipts
Route::get('/misc/receipt/print','Admin\ReceiptController@printStudentReceipt')->name('admin.student.receipt.print');

//manage unmanaged indexes
Route::get('manage-schedule','Index\IndexController@getScheduleIndex')->name('manage.schedule.home');
Route::get('manage-courses','Index\IndexController@getManageCourseIndex')->name('manage.courses.home');
Route::get('manage-students','Index\IndexController@getManageStudentIndex')->name('manage.students.home');
Route::get('manage-classes','Index\IndexController@getManageClassesIndex')->name('manage.classes.home');
Route::get('manage-all-fees','Index\IndexController@getManageFees')->name('manage.fees.home');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@welcome')->name('myeschool.index');

Route::get('/register','HomeController@register')->name('school.register');

Route::get('/login','HomeController@login')->name('login.validate');
Route::get('/about','HomeController@about')->name('home.about');
Route::get('/contact','HomeController@contact')->name('home.contact');
Route::get('/sales-reps','HomeController@salesReps')->name('home.sales_reps');
Route::post('/register-school','Misc\MiscController@regSchool');
Route::post('/login-user','Misc\MiscController@login');
//verify user
Route::get('/user/verify/{token}', 'Misc\MiscController@verifyUser');
Route::post('/user/verify-sms','Misc\MiscController@verifySMS');
Route::post('/logout','Misc\MiscController@logout')->name('user.logout');

//password resets
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.token');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');



//////////////////////////protected with permissions ////////////////////////////
///
Route::group(['middleware'=>'authenticated'],function (){
    Route::resources([
        'timetables'=>'Admin\TimeTableController',
    ]);
    Route::get('/dashboard', 'HomeController@dashboard')->name('myeschool.local.dashboard');
    //endpoints with the authentication
    Route::get('/teachers/endpoint','Misc\EndPointController@names')->name('teacher.names.endpoint');
    Route::get('/teachers-classes/endpoint','Misc\EndPointController@teacherClass')->name('teacher.classes.endpoint');

//items endpoint
    Route::get('/items/endpoint','Misc\EndPointController@items')->name('items.fees.endpoint');
    Route::get('/date/generation','Misc\EndPointController@generateYears');
//academic year endpoint
    Route::get('/date/academic/years','Misc\EndPointController@showAcademicYears')->name('date.academic.years');
///term endpoints
    Route::get('/date/acade/terms','Misc\EndPointController@showFromYearsTable');
    Route::get('/date/academic/terms','Misc\EndPointController@makeDataTableTerms')->name('date.academic.terms');
    Route::get('/date/terms/{name}','Misc\EndPointController@showTerms');
//fees endpoint particulars
    Route::get('/date/items/show-all','Misc\EndPointController@showAllItems');
    Route::get('/date/classes/show-all','Misc\EndPointController@showAllClasses');
//fees endpoint
    Route::get('/date/fees/class-distinct','Misc\EndPointController@feesDistinctClass')->name('date.fees.class_distinct');

//courses endpoint
    Route::get('/date/courses/show-all','Misc\EndPointController@allCourses')->name('date.courses.show.all');
    Route::get('/date/class-courses/show-all','Misc\EndPointController@allClassCourses')->name('date.class_courses.show.all');

    Route::get('/date/parents/all','Misc\EndPointController@showParents');

    Route::post('/submit_comment','Misc\ContactUsController@store')->name('user.contact.us');

//fees payment
    Route::get('/date/students/all/{id}','Misc\EndPointController@showParticularStudent');
    Route::get('/date/students/all/previous/{id}','Misc\EndPointController@showStudentPrevious');
    Route::get('/date/all/universities','Misc\EndPointController@getAllUniversities');
    Route::get('/date/all/universities/years','Misc\EndPointController@allYearsPassed');
});

Route::get('/time-tables/getTeachers/{id}','Admin\TimeTableController@getTeachers')->middleware('authenticated');

///manage sms routes
Route::group(['prefix'=>'manage-sms','middleware'=>'authenticated'],function (){
    Route::get('index','SMS\SMSController@index')->name('manage_all_sms.sms');
    Route::get('send','SMS\SMSController@create')->name('manage_all_sms.sms.send');
    //set staff for sms
    Route::get('sms-for-staff','SMS\SMSController@smsForStaff');
    Route::get('sms-for-students','SMS\SMSController@smsForStudent');
    Route::get('sms-for-parents','SMS\SMSController@smsForParent');
    Route::get('sms-for-parents/{class_id}','SMS\SMSController@getStudentForParentClass');
    Route::get('sms-for-class/{class_id}','SMS\SMSController@getStudentForClass');
    Route::post('send/{id?}','SMS\SMSController@sendSMS');
    Route::post('send-single/{id?}','SMS\SMSController@sendSingleSMS');
    Route::post('callback','SMS\SMSController@smsCallback')->name('sms.callback');
    //get sms details
    Route::get('sms-details','SMS\SMSController@getSMSDetailsIndex')->name('sms.details');
    Route::get('sms-details/{id}','SMS\SMSController@getSMSDetailParticular')->name('sms.details.index');
});
//////////////finance routes///////////////////////////
Route::get('finances','Finance\IndexController@index')->name('manage_all.finances')->middleware('authenticated');
Route::group(['prefix'=>'finances','middleware'=>'authenticated'],function(){
    Route::resources([
        'expenses'=>'Finance\Expense\ExpenseController',
        'expenses-categories'=>'Finance\Expense\ExpenseCategoryController',
        'income-categories'=>'Finance\Income\IncomeCategoryController',
        'incomes'=>'Finance\Income\IncomeController',
        'student-bills'=>'Finance\Bills\BillController',
        'payments'=>'Finance\Payments\CategoryController',
        'student-fees'=>'Finance\Fees\FeeController'
    ]);
    Route::post('bulk-delete','Finance\Expense\ExpenseCategoryController@bulkDelete');
    Route::post('income-cat-bulk-delete','Finance\Income\IncomeCategoryController@bulkDelete');
    Route::prefix('student-fees')->group(function (){
        Route::get('students/{id}','Finance\Fees\FeeController@getStudentForClass');
        Route::get('students-wallet/{id}','Finance\Fees\FeeController@getStudentWallet');
    });
    //Finance\History\TransactionHistoryController
    Route::prefix('transaction-history')->group(function (){
        Route::get('index','Finance\History\TransactionHistoryController@index')
            ->name('transaction_history.index');
        Route::post('index','Finance\History\TransactionHistoryController@filterResults');
    });
    Route::get('owing-students','Finance\NotificationController@index')->name('finance.notifications.index');
    Route::post('owing-students/search','Finance\NotificationController@searchStudent');
    Route::get('manage-bills','Index\IndexController@getManageFinanceBills')->name('finance.manage.bills.home');
    //print bills
    Route::get('print-bills','Finance\Bills\PrintController@index')->name('finance.print.bills.index');
    Route::post('print-bills','Finance\Bills\PrintController@fetchBills');
});
//notifications
Route::group(['prefix'=>'notifications','middleware'=>'authenticated'],function (){
    Route::get('index','Notifications\NotificationController@index')->name('notifications.index');
});
//manage exams
Route::group(['prefix'=>'examination','middleware'=>'authenticated'],function(){
    Route::get('','Index\IndexController@getManageExams')->name('manage.exams.index');
    Route::resources([
        'exam-approvals'=>'Examination\ApproveController',
        'remarks'=>'Admin\RemarkController',
    ]);
    Route::get('report-template','Admin\DetailController@getReportCardTemplate')->name('get.report.template');
    Route::get('report-template-add/{id}','Admin\DetailController@setSchoolTemplate');
    Route::get('submissions','Examination\SubmissionController@index')->name('examinations.submissions.index');
    Route::get('class/{id}','Examination\SubmissionController@getClassCourses');
    Route::post('reports','Examination\SubmissionController@getSubmissions');
});

//search on the header
Route::post('search-header','Home\SearchController@search');

resources/views/index/admin-settings.blade.php
@extends('admin.index')

@push('css')

@endpush


@section('title','Admin')


@section('main')
    <div class="main-content" id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 clear-padding-xs">
                    <h5 class="page-title"><i class="fa fa-cog"></i>SETTINGS</h5>
                    <div class="section-divider"></div>
                    <div class="dash-item first-dash-item">
                        <div class="dashboard-stats">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('general_settings.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>WEB SETTINGS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-cog"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-pencil-square-o"></i>
                                            website settings
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('institution_settings.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>INSTITUTION SETTINGS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-code"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-pencil-square-o"></i>
                                            all institution details
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="clearfix visible-sm"></div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('configuraton.student.profile.field')}}" class="btn btn-success">GO</a></h1>
                                            <p>STUDENT SETTINGS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-stumbleupon"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-pencil-square-o"></i>
                                            students admission fields
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('fee-approvals.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>FEES</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-money"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-pencil-square-o"></i>
                                            approve fees
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="dash-item">
                        <div class="dashboard-stats">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('admin.profile.show')}}" class="btn btn-success">GO</a></h1>
                                            <p>VIEW</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-eye"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-pencil-square-o"></i>
                                            View Profile
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('admin.passwords.show')}}" class="btn btn-success">GO</a></h1>
                                            <p>PASSWORD</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-lock"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-look"><i class="fa fa-lock"></i>
                                            Change Password
                                        </p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="menu-togggle-btn">
            <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection


@push('scripts')

@endpush

resources/views/index/manage-students.blade.php
@extends('admin.index')

@push('css')

@endpush


@section('title','Admin')


@section('main')
    <div class="main-content" id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 clear-padding-xs">
                    <h5 class="page-title"><i class="fa fa-clock-o"></i>MANAGE STUDENTS</h5>
                    <div class="section-divider"></div>
                    <div class="dash-item first-dash-item">
                        <div class="dashboard-stats">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('students.create')}}" class="btn btn-success">ADD</a></h1>
                                            <p>STUDENTS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-user-md"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-ex"><i class="fa fa-pencil-square-o"></i>Add Students</p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('students.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>ALL STUDENTS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-list"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-ex"><i class="fa fa-eye"></i>View All Students</p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="menu-togggle-btn">
            <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection


@push('scripts')

@endpush

resources/views/index/schedule.blade.php
@extends('admin.index')

@push('css')

@endpush


@section('title','Admin')


@section('main')
    <div class="main-content" id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 clear-padding-xs">
                    <h5 class="page-title"><i class="fa fa-clock-o"></i>MANAGE SCHEDULE</h5>
                    <div class="section-divider"></div>
                    <div class="dash-item first-dash-item">
                        <div class="dashboard-stats">
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('slots.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>SLOTS</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-clock-o"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-ex"><i class="fa fa-pencil-square-o"></i>Manage Slots</p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                            <div class="col-sm-6 col-md-3">
                                <div class="stat-item">
                                    <div class="stats">
                                        <div class="col-xs-8 count">
                                            <h1><a href="{{route('timetables.index')}}" class="btn btn-success">GO</a></h1>
                                            <p>TIME TABLE</p>
                                        </div>
                                        <div class="col-xs-4 icon">
                                            <i class="fa fa-calendar"></i>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="status">
                                        <p class="text-ex"><i class="fa fa-pencil-square"></i>Manage Timetable</p>
                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="menu-togggle-btn">
            <a href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
        </div>
        @include('admin.partials.footer')
    </div>
@endsection


@push('scripts')

@endpush